# Generated by Django 2.0.dev20170426002136 on 2017-08-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170801_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, help_text="Describe your project's used tech stack. (256 character limit)", max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('web-app', 'Web Apps'), ('android-app', 'Android Apps'), ('website', 'Websites'), ('ecommerce', 'e-Commerce'), ('plugins-extensions', 'Plugins & Extensions')], default='uncategorized', help_text='Tag your project for categorization.', max_length=60),
        ),
    ]
