# Generated by Django 2.0.dev20170426002136 on 2017-08-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170801_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Describe your project. (256 character limit)', max_length=256),
        ),
    ]
