# Generated by Django 2.0.dev20170426002136 on 2017-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170802_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='testfield',
            field=models.CharField(blank=True, help_text='A Test field', max_length=60),
        ),
    ]
