# Generated by Django 2.0.dev20170426002136 on 2017-08-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='testfield',
        ),
    ]
