# Generated by Django 2.0.dev20170426002136 on 2017-09-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170918_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_order',)},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='order',
            new_name='project_order',
        ),
    ]
