# Generated by Django 2.0.dev20170426002136 on 2017-09-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170918_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('my_order',)},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_order',
            new_name='my_order',
        ),
    ]
