# Generated by Django 2.0.dev20170426002136 on 2017-09-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20170919_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
    ]
