# Generated by Django 2.0.dev20170426002136 on 2017-08-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=0, help_text='Describe your project. (256 character limit)', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='NULL', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='NULL', help_text='Enter the link to your project. (256 character limit)', max_length=256),
            preserve_default=False,
        ),
    ]
