# Generated by Django 2.0.dev20170426002136 on 2017-08-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170801_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enabled',
            field=models.BooleanField(default=1, verbose_name='enabled'),
            preserve_default=False,
        ),
    ]
