# Generated by Django 2.0.dev20170426002136 on 2017-08-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/uploads/projects'),
        ),
    ]
