# Generated by Django 2.0.dev20170426002136 on 2017-09-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order',)},
        ),
    ]
