# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180823_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(blank=True, help_text="Image's alt text (60 character limit)", max_length=60),
        ),
    ]
