# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180823_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
    ]
