# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Your projects featured thumbnail image', upload_to='static/uploads/projects'),
        ),
    ]
