# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20180824_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, help_text='Enter the link to your project. (255 character limit)', max_length=255),
        ),
    ]
