# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20180824_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(blank=True, help_text='Enter the source code/git repo link to your project. (255 character limit)', max_length=255),
        ),
    ]
