# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Your projects featured thumbnail image (Download template here: <a href='//localhost:8000static/downloads/projectThumbTemplate.psd' downlod='//localhost:8000static/downloads/projectThumbTemplate.psd'>Thumbnail Template</a>)", upload_to='static/uploads/projects'),
        ),
    ]
