# Generated by Django 2.0.dev20170426002136 on 2017-08-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170814_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('case-studies', 'Web Apps'), ('tutorials', 'Tutorials'), ('project-logs', 'Project Logs')], default='uncategorized', help_text='Tag your post for categorization.', max_length=60),
        ),
    ]
