# Generated by Django 2.0.dev20170426002136 on 2017-04-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
