# Generated by Django 2.0.dev20170426002136 on 2017-07-31 22:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enabled',
            field=models.BooleanField(default=0, verbose_name='enabled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_description',
            field=models.CharField(default=False, help_text='150 character limit', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(help_text='60 character limit', max_length=60),
        ),
    ]
