# Generated by Django 2.0.dev20170426002136 on 2017-08-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='permalink',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
    ]
