# Generated by Django 2.0.dev20170426002136 on 2017-08-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='150 character limit', max_length=150)),
                ('position', models.CharField(help_text='60 character limit', max_length=60)),
                ('description', models.TextField(help_text='Describe your job position')),
                ('start_date', models.DateField(verbose_name='When you started working')),
                ('end_date', models.DateField(verbose_name='When you started working')),
                ('current', models.BooleanField(help_text='Are you currently working here?', verbose_name='disabled')),
            ],
        ),
    ]
