# Generated by Django 2.0.dev20170426002136 on 2017-08-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_insitution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insitution',
            new_name='Institution',
        ),
    ]
