# Generated by Django 2.0.dev20170426002136 on 2017-08-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20170817_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='skills',
            field=models.TextField(help_text='List your skills, seperate with commas. Just a regular text area.'),
        ),
    ]
