# Generated by Django 2.0.dev20170426002136 on 2017-09-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20170817_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='skillset',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institution',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillset',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
