# Generated by Django 2.0.dev20170426002136 on 2017-08-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20170816_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='current',
            field=models.BooleanField(help_text='Are you currently working at this position?', verbose_name='Current Position'),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='When you stopped working'),
        ),
    ]
