# Generated by Django 2.0.dev20170426002136 on 2017-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20170816_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(help_text='Degree/Diploma name', max_length=150)),
                ('name', models.CharField(help_text='Name of institution', max_length=150)),
                ('end_date', models.DateField(verbose_name='Completion Date')),
            ],
        ),
    ]
