# Generated by Django 2.0.dev20170426002136 on 2017-08-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20170816_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Do you want to show this on resume?', verbose_name='Enable Position'),
        ),
    ]
