# Generated by Django 2.0.dev20170426002136 on 2017-08-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_job_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(help_text='Information about the achievement', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of skillset (i.e, Front-end/Services)', max_length=150)),
                ('skills', models.CharField(help_text='List your skills, seperate with commas. Just a regular text area.', max_length=150)),
            ],
        ),
    ]
