# Generated by Django 2.0.dev20170426002136 on 2017-08-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_achievement_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='item',
            field=models.TextField(help_text='Information about the achievement'),
        ),
    ]
